//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApparatus.Lang {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class es_ES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal es_ES() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectApparatus.Lang.es_ES", typeof(es_ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Object.
        /// </summary>
        internal static string _object {
            get {
                return ResourceManager.GetString("object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modifica Salto.
        /// </summary>
        internal static string adjust_jump_height {
            get {
                return ResourceManager.GetString("adjust_jump_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modifica cuanto quieres saltar.
        /// </summary>
        internal static string adjust_jump_height_descr {
            get {
                return ResourceManager.GetString("adjust_jump_height_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modifica Velocidad Sprint.
        /// </summary>
        internal static string adjust_sprint_speed {
            get {
                return ResourceManager.GetString("adjust_sprint_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modifica la velocidad a la que quieres ir..
        /// </summary>
        internal static string adjust_sprint_speed_descr {
            get {
                return ResourceManager.GetString("adjust_sprint_speed_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modifica Velocidad andando.
        /// </summary>
        internal static string adjust_walk_speed {
            get {
                return ResourceManager.GetString("adjust_walk_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modifica la velocidad a la que quieres ir..
        /// </summary>
        internal static string adjust_walk_speed_descr {
            get {
                return ResourceManager.GetString("adjust_walk_speed_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enemigos Agresivos.
        /// </summary>
        internal static string aggro_enemies {
            get {
                return ResourceManager.GetString("aggro_enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los enemigos se fijarán en este jugador..
        /// </summary>
        internal static string aggro_enemies_descr_1 {
            get {
                return ResourceManager.GetString("aggro_enemies_descr_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doesn&apos;t work on most monsters, works best on Crawlers &amp; Spiders..
        /// </summary>
        internal static string aggro_enemies_descr_2 {
            get {
                return ResourceManager.GetString("aggro_enemies_descr_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All Jetpacks Explode.
        /// </summary>
        internal static string all_jetpacks_explode {
            get {
                return ResourceManager.GetString("all_jetpacks_explode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a When a player tries to equip a jetpack they will be greeted with an explosion..
        /// </summary>
        internal static string all_jetpacks_explode_descr {
            get {
                return ResourceManager.GetString("all_jetpacks_explode_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Always Show Clock.
        /// </summary>
        internal static string always_show_clock {
            get {
                return ResourceManager.GetString("always_show_clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Displays the clock even when you are in the facility..
        /// </summary>
        internal static string always_show_clock_descr {
            get {
                return ResourceManager.GetString("always_show_clock_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply.
        /// </summary>
        internal static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attack Players at Deposit Desk.
        /// </summary>
        internal static string attack_players_at_deposit_desk {
            get {
                return ResourceManager.GetString("attack_players_at_deposit_desk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forces the tentacle monster to attack, killing a nearby player..
        /// </summary>
        internal static string attack_players_at_deposit_desk_descr {
            get {
                return ResourceManager.GetString("attack_players_at_deposit_desk_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Big Loot.
        /// </summary>
        internal static string big_loot {
            get {
                return ResourceManager.GetString("big_loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forces the game to render in full resolution..
        /// </summary>
        internal static string camera_res_descr_1 {
            get {
                return ResourceManager.GetString("camera_res_descr_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;color=#ff0000&gt;You will need to leave the game for this to activate.&lt;/color&gt;.
        /// </summary>
        internal static string camera_res_descr_2 {
            get {
                return ResourceManager.GetString("camera_res_descr_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centered Indicators.
        /// </summary>
        internal static string centered_indicators {
            get {
                return ResourceManager.GetString("centered_indicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Displays the above indicators at the center of the screen..
        /// </summary>
        internal static string centered_indicators_descr {
            get {
                return ResourceManager.GetString("centered_indicators_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Changelog.
        /// </summary>
        internal static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Charge Any Item.
        /// </summary>
        internal static string charge_any_item {
            get {
                return ResourceManager.GetString("charge_any_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to put any grabbable item in the charger..
        /// </summary>
        internal static string charge_any_item_descr {
            get {
                return ResourceManager.GetString("charge_any_item_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close All Mechanical Doors.
        /// </summary>
        internal static string close_all_mechanical_doors {
            get {
                return ResourceManager.GetString("close_all_mechanical_doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closes all mechanical doors..
        /// </summary>
        internal static string close_all_mechanical_doors_descr {
            get {
                return ResourceManager.GetString("close_all_mechanical_doors_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colors.
        /// </summary>
        internal static string colors {
            get {
                return ResourceManager.GetString("colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credits.
        /// </summary>
        internal static string credits {
            get {
                return ResourceManager.GetString("credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crosshair.
        /// </summary>
        internal static string crosshair {
            get {
                return ResourceManager.GetString("crosshair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Displays a crosshair on the screen..
        /// </summary>
        internal static string crosshair_descr {
            get {
                return ResourceManager.GetString("crosshair_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Damage.
        /// </summary>
        internal static string damage {
            get {
                return ResourceManager.GetString("damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Damages the player for a given amount..
        /// </summary>
        internal static string damage_descr {
            get {
                return ResourceManager.GetString("damage_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Days Left.
        /// </summary>
        internal static string days_left {
            get {
                return ResourceManager.GetString("days_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debug Log.
        /// </summary>
        internal static string dbg_log {
            get {
                return ResourceManager.GetString("dbg_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For developers, if you use just want to use menu you should keep this off..
        /// </summary>
        internal static string dbg_log_desc {
            get {
                return ResourceManager.GetString("dbg_log_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dead Player List.
        /// </summary>
        internal static string dead_players {
            get {
                return ResourceManager.GetString("dead_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows a list of currently dead players..
        /// </summary>
        internal static string dead_players_descr {
            get {
                return ResourceManager.GetString("dead_players_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Object.
        /// </summary>
        internal static string del_object {
            get {
                return ResourceManager.GetString("del_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete the item you are holding..
        /// </summary>
        internal static string del_object_desc {
            get {
                return ResourceManager.GetString("del_object_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete All Enemies.
        /// </summary>
        internal static string delete_all_enemies {
            get {
                return ResourceManager.GetString("delete_all_enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deletes all enemies..
        /// </summary>
        internal static string delete_all_enemies_descr {
            get {
                return ResourceManager.GetString("delete_all_enemies_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Demigod.
        /// </summary>
        internal static string demigod {
            get {
                return ResourceManager.GetString("demigod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automatically refills the selected player&apos;s health if below zero..
        /// </summary>
        internal static string demigod_descr {
            get {
                return ResourceManager.GetString("demigod_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disable Depth of Field.
        /// </summary>
        internal static string disable_dof {
            get {
                return ResourceManager.GetString("disable_dof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disables the depth of field effect..
        /// </summary>
        internal static string disable_dof_descr {
            get {
                return ResourceManager.GetString("disable_dof_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disable Fall Damage.
        /// </summary>
        internal static string disable_fall_damage {
            get {
                return ResourceManager.GetString("disable_fall_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You no longer take fall damage..
        /// </summary>
        internal static string disable_fall_damage_descr {
            get {
                return ResourceManager.GetString("disable_fall_damage_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disable Fog.
        /// </summary>
        internal static string disable_fog {
            get {
                return ResourceManager.GetString("disable_fog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disables the fog effect..
        /// </summary>
        internal static string disable_fog_descr {
            get {
                return ResourceManager.GetString("disable_fog_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disable Interact Cooldowns.
        /// </summary>
        internal static string disable_interact_cooldowns {
            get {
                return ResourceManager.GetString("disable_interact_cooldowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disables all interact cooldowns (e.g., noisemakers, toilets, etc)..
        /// </summary>
        internal static string disable_interact_cooldowns_descr {
            get {
                return ResourceManager.GetString("disable_interact_cooldowns_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disable Visor.
        /// </summary>
        internal static string disable_visor {
            get {
                return ResourceManager.GetString("disable_visor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disables the visor from your helmet in first person..
        /// </summary>
        internal static string disable_visor_descr {
            get {
                return ResourceManager.GetString("disable_visor_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display Days Left.
        /// </summary>
        internal static string display_days_left {
            get {
                return ResourceManager.GetString("display_days_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows the time you have left to meet quota..
        /// </summary>
        internal static string display_days_left_descr {
            get {
                return ResourceManager.GetString("display_days_left_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Distance.
        /// </summary>
        internal static string display_distance {
            get {
                return ResourceManager.GetString("display_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows the distance between you and the entity..
        /// </summary>
        internal static string display_distance_esp_descr {
            get {
                return ResourceManager.GetString("display_distance_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display Group Credits.
        /// </summary>
        internal static string display_group_credits {
            get {
                return ResourceManager.GetString("display_group_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows how many credits you have..
        /// </summary>
        internal static string display_group_credits_descr {
            get {
                return ResourceManager.GetString("display_group_credits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Health.
        /// </summary>
        internal static string display_hp {
            get {
                return ResourceManager.GetString("display_hp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows players&apos; health..
        /// </summary>
        internal static string display_hp_esp_descr {
            get {
                return ResourceManager.GetString("display_hp_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display Loot In Ship.
        /// </summary>
        internal static string display_loot_in_ship {
            get {
                return ResourceManager.GetString("display_loot_in_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows the value of all the items you have gathered in the ship..
        /// </summary>
        internal static string display_loot_in_ship_descr {
            get {
                return ResourceManager.GetString("display_loot_in_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display Quota.
        /// </summary>
        internal static string display_quota {
            get {
                return ResourceManager.GetString("display_quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows the current quota..
        /// </summary>
        internal static string display_quota_descr {
            get {
                return ResourceManager.GetString("display_quota_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Is Speaking.
        /// </summary>
        internal static string display_speaking {
            get {
                return ResourceManager.GetString("display_speaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows if the player is speaking..
        /// </summary>
        internal static string display_speaking_esp_descr {
            get {
                return ResourceManager.GetString("display_speaking_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Value.
        /// </summary>
        internal static string display_worth {
            get {
                return ResourceManager.GetString("display_worth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows items&apos; value..
        /// </summary>
        internal static string display_worth_esp_descr {
            get {
                return ResourceManager.GetString("display_worth_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distance.
        /// </summary>
        internal static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Door.
        /// </summary>
        internal static string door {
            get {
                return ResourceManager.GetString("door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doors.
        /// </summary>
        internal static string door_esp {
            get {
                return ResourceManager.GetString("door_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows all doors..
        /// </summary>
        internal static string door_esp_descr {
            get {
                return ResourceManager.GetString("door_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enabled.
        /// </summary>
        internal static string enable_esp {
            get {
                return ResourceManager.GetString("enable_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enables the ESP..
        /// </summary>
        internal static string enable_esp_descr {
            get {
                return ResourceManager.GetString("enable_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enemy.
        /// </summary>
        internal static string enemy {
            get {
                return ResourceManager.GetString("enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enemy Distance Limit.
        /// </summary>
        internal static string enemy_distance_limit {
            get {
                return ResourceManager.GetString("enemy_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle to set the enemy distance limit..
        /// </summary>
        internal static string enemy_distance_limit_descr {
            get {
                return ResourceManager.GetString("enemy_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enemies.
        /// </summary>
        internal static string enemy_esp {
            get {
                return ResourceManager.GetString("enemy_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows all enemies..
        /// </summary>
        internal static string enemy_esp_descr {
            get {
                return ResourceManager.GetString("enemy_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrance.
        /// </summary>
        internal static string entrance {
            get {
                return ResourceManager.GetString("entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESP.
        /// </summary>
        internal static string esp {
            get {
                return ResourceManager.GetString("esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explode All Mines.
        /// </summary>
        internal static string explode_all_mines {
            get {
                return ResourceManager.GetString("explode_all_mines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explodes every single mine on the level..
        /// </summary>
        internal static string explode_all_mines_descr {
            get {
                return ResourceManager.GetString("explode_all_mines_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FastLadder Climbing.
        /// </summary>
        internal static string fast_ladder_climbing {
            get {
                return ResourceManager.GetString("fast_ladder_climbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instantly climbs up ladders..
        /// </summary>
        internal static string fast_ladder_climbing_descr {
            get {
                return ResourceManager.GetString("fast_ladder_climbing_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field of View.
        /// </summary>
        internal static string fov {
            get {
                return ResourceManager.GetString("fov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Give Credits.
        /// </summary>
        internal static string give_credits {
            get {
                return ResourceManager.GetString("give_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Give your group however many credits you want. (Doesn&apos;t apply to quota).
        /// </summary>
        internal static string give_credits_descr {
            get {
                return ResourceManager.GetString("give_credits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a God Mode.
        /// </summary>
        internal static string god_mode {
            get {
                return ResourceManager.GetString("god_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prevents you from taking any damage..
        /// </summary>
        internal static string god_mode_descr {
            get {
                return ResourceManager.GetString("god_mode_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graphics.
        /// </summary>
        internal static string graphics {
            get {
                return ResourceManager.GetString("graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group Credits.
        /// </summary>
        internal static string group_credits {
            get {
                return ResourceManager.GetString("group_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set Credits.
        /// </summary>
        internal static string group_set_credits {
            get {
                return ResourceManager.GetString("group_set_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set however many credits you want. (Doesn&apos;t apply to quota).
        /// </summary>
        internal static string group_set_credits_desc {
            get {
                return ResourceManager.GetString("group_set_credits_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Heal.
        /// </summary>
        internal static string heal {
            get {
                return ResourceManager.GetString("heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Heals the player for a given amount..
        /// </summary>
        internal static string heal_descr {
            get {
                return ResourceManager.GetString("heal_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hear Everyone.
        /// </summary>
        internal static string hear_everyone {
            get {
                return ResourceManager.GetString("hear_everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to hear everyone no matter the distance..
        /// </summary>
        internal static string hear_everyone_descr {
            get {
                return ResourceManager.GetString("hear_everyone_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set Held Item Scrap Value.
        /// </summary>
        internal static string held_item_val {
            get {
                return ResourceManager.GetString("held_item_val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sets the value of the item you are holding to what you have selected above..
        /// </summary>
        internal static string held_item_val_desc {
            get {
                return ResourceManager.GetString("held_item_val_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello world!.
        /// </summary>
        internal static string hello_world {
            get {
                return ResourceManager.GetString("hello_world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hide Objects.
        /// </summary>
        internal static string hide_objects {
            get {
                return ResourceManager.GetString("hide_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hides spammed objects from the selected player..
        /// </summary>
        internal static string hide_objects_descr {
            get {
                return ResourceManager.GetString("hide_objects_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Infinite Charge.
        /// </summary>
        internal static string infinite_charge {
            get {
                return ResourceManager.GetString("infinite_charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prevents your items from losing any charge..
        /// </summary>
        internal static string infinite_charge_descr {
            get {
                return ResourceManager.GetString("infinite_charge_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Infinite Item Use.
        /// </summary>
        internal static string infinite_items {
            get {
                return ResourceManager.GetString("infinite_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to infinitely use items like the gift box and stun grenade. (Buggy).
        /// </summary>
        internal static string infinite_items_descr {
            get {
                return ResourceManager.GetString("infinite_items_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Infinite Shotgun Ammo.
        /// </summary>
        internal static string infinite_shotgun_ammo {
            get {
                return ResourceManager.GetString("infinite_shotgun_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prevents you from out of ammo..
        /// </summary>
        internal static string infinite_shotgun_ammo_descr {
            get {
                return ResourceManager.GetString("infinite_shotgun_ammo_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Infinite Stamina.
        /// </summary>
        internal static string infinite_stam {
            get {
                return ResourceManager.GetString("infinite_stam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prevents you from losing any stamina..
        /// </summary>
        internal static string infinite_stam_descr {
            get {
                return ResourceManager.GetString("infinite_stam_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Infinite Zap Gun.
        /// </summary>
        internal static string infinite_zap_gun {
            get {
                return ResourceManager.GetString("infinite_zap_gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Infinitely stuns enemies with the zap-gun..
        /// </summary>
        internal static string infinite_zap_gun_descr {
            get {
                return ResourceManager.GetString("infinite_zap_gun_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instant Interactions.
        /// </summary>
        internal static string instant_interactions {
            get {
                return ResourceManager.GetString("instant_interactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Makes all hold interactions instantaneous..
        /// </summary>
        internal static string instant_interactions_descr {
            get {
                return ResourceManager.GetString("instant_interactions_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interact Through Walls.
        /// </summary>
        internal static string interact_through_walls {
            get {
                return ResourceManager.GetString("interact_through_walls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to interact with anything through walls..
        /// </summary>
        internal static string interact_through_walls_descr {
            get {
                return ResourceManager.GetString("interact_through_walls_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invisibility.
        /// </summary>
        internal static string invisibility {
            get {
                return ResourceManager.GetString("invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players will not be able to see you..
        /// </summary>
        internal static string invisibility_desc {
            get {
                return ResourceManager.GetString("invisibility_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item Distance Limit.
        /// </summary>
        internal static string item_distance_limit {
            get {
                return ResourceManager.GetString("item_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle to set the item distance limit..
        /// </summary>
        internal static string item_distance_limit_descr {
            get {
                return ResourceManager.GetString("item_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Items.
        /// </summary>
        internal static string item_esp {
            get {
                return ResourceManager.GetString("item_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows all items..
        /// </summary>
        internal static string item_esp_descr {
            get {
                return ResourceManager.GetString("item_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kill.
        /// </summary>
        internal static string kill {
            get {
                return ResourceManager.GetString("kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kill All Enemies.
        /// </summary>
        internal static string kill_all_enemies {
            get {
                return ResourceManager.GetString("kill_all_enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kills all enemies..
        /// </summary>
        internal static string kill_all_enemies_descr {
            get {
                return ResourceManager.GetString("kill_all_enemies_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kills the currently selected player..
        /// </summary>
        internal static string kill_descr {
            get {
                return ResourceManager.GetString("kill_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Land Ship.
        /// </summary>
        internal static string land_ship {
            get {
                return ResourceManager.GetString("land_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lands the ship..
        /// </summary>
        internal static string land_ship_descr {
            get {
                return ResourceManager.GetString("land_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Landmine.
        /// </summary>
        internal static string landmine {
            get {
                return ResourceManager.GetString("landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle to set the landmine distance limit..
        /// </summary>
        internal static string landmine_distance_limit_descr {
            get {
                return ResourceManager.GetString("landmine_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Landmines.
        /// </summary>
        internal static string landmine_esp {
            get {
                return ResourceManager.GetString("landmine_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows all landmines..
        /// </summary>
        internal static string landmine_esp_descr {
            get {
                return ResourceManager.GetString("landmine_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Light Show.
        /// </summary>
        internal static string light_show {
            get {
                return ResourceManager.GetString("light_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rapidly turns on/off the light switch and TV..
        /// </summary>
        internal static string light_show_descr {
            get {
                return ResourceManager.GetString("light_show_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loot.
        /// </summary>
        internal static string loot {
            get {
                return ResourceManager.GetString("loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loot in ship.
        /// </summary>
        internal static string loot_in_ship {
            get {
                return ResourceManager.GetString("loot_in_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medium Loot.
        /// </summary>
        internal static string medium_loot {
            get {
                return ResourceManager.GetString("medium_loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Landmine Distance Limit.
        /// </summary>
        internal static string mine_distance_limit {
            get {
                return ResourceManager.GetString("mine_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Misc.
        /// </summary>
        internal static string misc {
            get {
                return ResourceManager.GetString("misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Moons.
        /// </summary>
        internal static string moons {
            get {
                return ResourceManager.GetString("moons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Night Vision.
        /// </summary>
        internal static string night_vision {
            get {
                return ResourceManager.GetString("night_vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to see in the dark..
        /// </summary>
        internal static string night_vision_descr {
            get {
                return ResourceManager.GetString("night_vision_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not Holding An Object.
        /// </summary>
        internal static string no_held_object {
            get {
                return ResourceManager.GetString("no_held_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No More Credits.
        /// </summary>
        internal static string no_more_credits {
            get {
                return ResourceManager.GetString("no_more_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prevents your group from receiving any credits. (Doesn&apos;t apply to quota).
        /// </summary>
        internal static string no_more_credits_descr {
            get {
                return ResourceManager.GetString("no_more_credits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noclip.
        /// </summary>
        internal static string noclip {
            get {
                return ResourceManager.GetString("noclip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to fly and clip through walls..
        /// </summary>
        internal static string noclip_descr {
            get {
                return ResourceManager.GetString("noclip_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Object To Spawn.
        /// </summary>
        internal static string obj_to_spawn {
            get {
                return ResourceManager.GetString("obj_to_spawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Object Spam.
        /// </summary>
        internal static string object_spam {
            get {
                return ResourceManager.GetString("object_spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spam places objects on the player to annoy/trap them..
        /// </summary>
        internal static string object_spam_descr {
            get {
                return ResourceManager.GetString("object_spam_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One Hand All Objects.
        /// </summary>
        internal static string one_hand_all_objects {
            get {
                return ResourceManager.GetString("one_hand_all_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to one-hand any two-handed objects..
        /// </summary>
        internal static string one_hand_all_objects_descr {
            get {
                return ResourceManager.GetString("one_hand_all_objects_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open All Mechanical Doors.
        /// </summary>
        internal static string open_all_mechanical_doors {
            get {
                return ResourceManager.GetString("open_all_mechanical_doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opens all mechanical doors..
        /// </summary>
        internal static string open_all_mechanical_doors_descr {
            get {
                return ResourceManager.GetString("open_all_mechanical_doors_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Place Anywhere.
        /// </summary>
        internal static string place_anywhere {
            get {
                return ResourceManager.GetString("place_anywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Place objects from the ship anywhere you want..
        /// </summary>
        internal static string place_anywhere_descr {
            get {
                return ResourceManager.GetString("place_anywhere_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player.
        /// </summary>
        internal static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        internal static string player_esp {
            get {
                return ResourceManager.GetString("player_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        internal static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows all players..
        /// </summary>
        internal static string players_esp_descr {
            get {
                return ResourceManager.GetString("players_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Possess Nearest Enemy.
        /// </summary>
        internal static string possess_nearest_enemy {
            get {
                return ResourceManager.GetString("possess_nearest_enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Possesses the nearest enemy. (Note: You will be visibily within the enemy.).
        /// </summary>
        internal static string possess_nearest_enemy_descr {
            get {
                return ResourceManager.GetString("possess_nearest_enemy_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profit Quota.
        /// </summary>
        internal static string profit_quota {
            get {
                return ResourceManager.GetString("profit_quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Weight.
        /// </summary>
        internal static string remove_weight {
            get {
                return ResourceManager.GetString("remove_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removes speed limitations caused by item weight..
        /// </summary>
        internal static string remove_weight_descr {
            get {
                return ResourceManager.GetString("remove_weight_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Full Render Resolution.
        /// </summary>
        internal static string render_resolution {
            get {
                return ResourceManager.GetString("render_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respawn.
        /// </summary>
        internal static string respawn {
            get {
                return ResourceManager.GetString("respawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respawns you. You will be invisible to both players and enemies..
        /// </summary>
        internal static string respawn_descr {
            get {
                return ResourceManager.GetString("respawn_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Language.
        /// </summary>
        internal static string select_language {
            get {
                return ResourceManager.GetString("select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected Player.
        /// </summary>
        internal static string selected_player {
            get {
                return ResourceManager.GetString("selected_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Self.
        /// </summary>
        internal static string self {
            get {
                return ResourceManager.GetString("self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Message.
        /// </summary>
        internal static string send_message_misc {
            get {
                return ResourceManager.GetString("send_message_misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anonymously sends a message in chat..
        /// </summary>
        internal static string send_message_misc_descr {
            get {
                return ResourceManager.GetString("send_message_misc_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Message.
        /// </summary>
        internal static string send_message_player {
            get {
                return ResourceManager.GetString("send_message_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sends a message in chat as the selected player..
        /// </summary>
        internal static string send_message_player_descr {
            get {
                return ResourceManager.GetString("send_message_player_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Signal.
        /// </summary>
        internal static string send_signal {
            get {
                return ResourceManager.GetString("send_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remotely sends a signal..
        /// </summary>
        internal static string send_signal_descr {
            get {
                return ResourceManager.GetString("send_signal_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensitive Landmines.
        /// </summary>
        internal static string sensitive_landmines {
            get {
                return ResourceManager.GetString("sensitive_landmines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automatically detonates landmines when a player is in kill range..
        /// </summary>
        internal static string sensitive_landmines_descr {
            get {
                return ResourceManager.GetString("sensitive_landmines_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set Quota.
        /// </summary>
        internal static string set_quota {
            get {
                return ResourceManager.GetString("set_quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to set the quota. (Host only).
        /// </summary>
        internal static string set_quota_descr {
            get {
                return ResourceManager.GetString("set_quota_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ship.
        /// </summary>
        internal static string ship {
            get {
                return ResourceManager.GetString("ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ships.
        /// </summary>
        internal static string ship_esp {
            get {
                return ResourceManager.GetString("ship_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows the ship..
        /// </summary>
        internal static string ship_esp_descr {
            get {
                return ResourceManager.GetString("ship_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Small Loot.
        /// </summary>
        internal static string small_loot {
            get {
                return ResourceManager.GetString("small_loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spam Message.
        /// </summary>
        internal static string spam_message_misc {
            get {
                return ResourceManager.GetString("spam_message_misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anonymously spams a message in chat..
        /// </summary>
        internal static string spam_message_misc_descr {
            get {
                return ResourceManager.GetString("spam_message_misc_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spam Message.
        /// </summary>
        internal static string spam_message_player {
            get {
                return ResourceManager.GetString("spam_message_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spams the message in chat as the selected player..
        /// </summary>
        internal static string spam_message_player_descr {
            get {
                return ResourceManager.GetString("spam_message_player_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spawn Enemy.
        /// </summary>
        internal static string spawn_enemy {
            get {
                return ResourceManager.GetString("spawn_enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spawns a random enemy on the selected player. Requires host..
        /// </summary>
        internal static string spawn_enemy_descr {
            get {
                return ResourceManager.GetString("spawn_enemy_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spawn Object.
        /// </summary>
        internal static string spawn_object {
            get {
                return ResourceManager.GetString("spawn_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Must be host to use. If object is more than one word use spaces and other words will be lowercase. Examples include Apparatus, Key, Red soda etc.
        /// </summary>
        internal static string spawn_object_desc {
            get {
                return ResourceManager.GetString("spawn_object_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Ship.
        /// </summary>
        internal static string start_ship {
            get {
                return ResourceManager.GetString("start_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ship will leave the planet it&apos;s currently on..
        /// </summary>
        internal static string start_ship_descr {
            get {
                return ResourceManager.GetString("start_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam Hazards.
        /// </summary>
        internal static string steam_hazard {
            get {
                return ResourceManager.GetString("steam_hazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows all hazard zones..
        /// </summary>
        internal static string steam_hazard_esp_descr {
            get {
                return ResourceManager.GetString("steam_hazard_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam Profile.
        /// </summary>
        internal static string steam_profile {
            get {
                return ResourceManager.GetString("steam_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opens the selected player&apos;s steam profile in your overlay..
        /// </summary>
        internal static string steam_profile_descr {
            get {
                return ResourceManager.GetString("steam_profile_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam Valve.
        /// </summary>
        internal static string steam_valve {
            get {
                return ResourceManager.GetString("steam_valve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop Possessing.
        /// </summary>
        internal static string stop_possessing {
            get {
                return ResourceManager.GetString("stop_possessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stops possessing the currently possessed enemy..
        /// </summary>
        internal static string stop_possessing_descr {
            get {
                return ResourceManager.GetString("stop_possessing_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suicide.
        /// </summary>
        internal static string suicide {
            get {
                return ResourceManager.GetString("suicide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kills local player..
        /// </summary>
        internal static string suicide_descr {
            get {
                return ResourceManager.GetString("suicide_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Take Credits.
        /// </summary>
        internal static string take_credits {
            get {
                return ResourceManager.GetString("take_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtract from your group however many credits you want. (Doesn&apos;t apply to quota).
        /// </summary>
        internal static string take_credits_desc {
            get {
                return ResourceManager.GetString("take_credits_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Taunt Slide.
        /// </summary>
        internal static string taunt_slide {
            get {
                return ResourceManager.GetString("taunt_slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to emote and move at the same time..
        /// </summary>
        internal static string taunt_slide_descr {
            get {
                return ResourceManager.GetString("taunt_slide_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teleport All Items.
        /// </summary>
        internal static string teleport_all_items {
            get {
                return ResourceManager.GetString("teleport_all_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teleports all items on the planet to you..
        /// </summary>
        internal static string teleport_all_items_descr {
            get {
                return ResourceManager.GetString("teleport_all_items_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teleport Enemies To.
        /// </summary>
        internal static string teleport_enemies_to {
            get {
                return ResourceManager.GetString("teleport_enemies_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teleports all enemies to the currently selected player..
        /// </summary>
        internal static string teleport_enemies_to_descr {
            get {
                return ResourceManager.GetString("teleport_enemies_to_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teleport Player To Ship.
        /// </summary>
        internal static string teleport_player_to_ship {
            get {
                return ResourceManager.GetString("teleport_player_to_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teleports the selected into the ship. (Host only).
        /// </summary>
        internal static string teleport_player_to_ship_descr {
            get {
                return ResourceManager.GetString("teleport_player_to_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teleport To.
        /// </summary>
        internal static string teleport_to {
            get {
                return ResourceManager.GetString("teleport_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teleports you to the currently selected player..
        /// </summary>
        internal static string teleport_to_descr {
            get {
                return ResourceManager.GetString("teleport_to_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teleport To Ship.
        /// </summary>
        internal static string teleport_to_ship {
            get {
                return ResourceManager.GetString("teleport_to_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teleports you into the ship..
        /// </summary>
        internal static string teleport_to_ship_descr {
            get {
                return ResourceManager.GetString("teleport_to_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terminal Noisemaker.
        /// </summary>
        internal static string terminal_noisemaker {
            get {
                return ResourceManager.GetString("terminal_noisemaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plays a very annoying noise from the terminal..
        /// </summary>
        internal static string terminal_noisemaker_descr {
            get {
                return ResourceManager.GetString("terminal_noisemaker_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press INSERT.
        /// </summary>
        internal static string tgl_insert {
            get {
                return ResourceManager.GetString("tgl_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Theme.
        /// </summary>
        internal static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thirdperson.
        /// </summary>
        internal static string thirdperson {
            get {
                return ResourceManager.GetString("thirdperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tooltips.
        /// </summary>
        internal static string tooltips {
            get {
                return ResourceManager.GetString("tooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows information about the currently hovered menu item..
        /// </summary>
        internal static string tooltips_descr {
            get {
                return ResourceManager.GetString("tooltips_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turret.
        /// </summary>
        internal static string turret {
            get {
                return ResourceManager.GetString("turret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turret Distance Limit.
        /// </summary>
        internal static string turret_distance_limit {
            get {
                return ResourceManager.GetString("turret_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle to set the turret distance limit..
        /// </summary>
        internal static string turret_distance_limit_descr {
            get {
                return ResourceManager.GetString("turret_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turrets.
        /// </summary>
        internal static string turret_esp {
            get {
                return ResourceManager.GetString("turret_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows all turrets..
        /// </summary>
        internal static string turret_esp_descr {
            get {
                return ResourceManager.GetString("turret_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;ve already unlocked all upgrades..
        /// </summary>
        internal static string u_alrd_unlc_all {
            get {
                return ResourceManager.GetString("u_alrd_unlc_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unlock All Suits.
        /// </summary>
        internal static string unlc_all_suits {
            get {
                return ResourceManager.GetString("unlc_all_suits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unlocks All Suits..
        /// </summary>
        internal static string unlc_all_suits_descr {
            get {
                return ResourceManager.GetString("unlc_all_suits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unlock All Upgrades.
        /// </summary>
        internal static string unlc_all_upgrd_ship {
            get {
                return ResourceManager.GetString("unlc_all_upgrd_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unlocks all ship upgrades..
        /// </summary>
        internal static string unlc_all_upgrd_ship_descr {
            get {
                return ResourceManager.GetString("unlc_all_upgrd_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Grab Distance Limit.
        /// </summary>
        internal static string unlimited_grab_distance {
            get {
                return ResourceManager.GetString("unlimited_grab_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to interact with anything no matter the distance..
        /// </summary>
        internal static string unlimited_grab_distance_descr {
            get {
                return ResourceManager.GetString("unlimited_grab_distance_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unlock.
        /// </summary>
        internal static string unlock {
            get {
                return ResourceManager.GetString("unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unlock All Doors.
        /// </summary>
        internal static string unlock_all_door {
            get {
                return ResourceManager.GetString("unlock_all_door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unlocks all locked doors..
        /// </summary>
        internal static string unlock_all_door_descr {
            get {
                return ResourceManager.GetString("unlock_all_door_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Untargetable.
        /// </summary>
        internal static string untargetable {
            get {
                return ResourceManager.GetString("untargetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Makes all the enemies ignore you..
        /// </summary>
        internal static string untargetable_desc {
            get {
                return ResourceManager.GetString("untargetable_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upgrades.
        /// </summary>
        internal static string upgrades {
            get {
                return ResourceManager.GetString("upgrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use Pocketed Items.
        /// </summary>
        internal static string use_pocket_items {
            get {
                return ResourceManager.GetString("use_pocket_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Any weapon you have in your inventory will be used for a cool attack..
        /// </summary>
        internal static string use_pocket_items_desc {
            get {
                return ResourceManager.GetString("use_pocket_items_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valve.
        /// </summary>
        internal static string valve {
            get {
                return ResourceManager.GetString("valve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abuelo Racista.
        /// </summary>
        internal static string watermark {
            get {
                return ResourceManager.GetString("watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to Project Apparatus.
        /// </summary>
        internal static string wlc_stp_1 {
            get {
                return ResourceManager.GetString("wlc_stp_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you have suggestions, please create a pull request in the repo or reply to the UC thread..
        /// </summary>
        internal static string wlc_stp_2 {
            get {
                return ResourceManager.GetString("wlc_stp_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you find bugs, please provide some steps on how to reproduce the problem and create an issue or pull request in the repo or reply to the UC thread.
        /// </summary>
        internal static string wlc_stp_3 {
            get {
                return ResourceManager.GetString("wlc_stp_3", resourceCulture);
            }
        }
    }
}
